{% set version = "0.19.2" %}

package:
  name: pyrsistent
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-{{ version }}.tar.gz
  sha256: bfa0351be89c9fcbcb8c9879b826f4353be10f58f8a677efab0c017bf7137ec2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyrsistent
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/tobgu/pyrsistent/
  license: MIT
  license_family: MIT
  license_file: LICENSE.mit
  summary: Persistent/Functional/Immutable data structures

extra:
  recipe-maintainers:
    - ocefpaf
